trigger:
- master

jobs:
  - job: 'BuildPackage'
    strategy:
      matrix:
        # linux:
        #   imageName: 'ubuntu-18.04'
        #   rid: 'linux-x64'
        # mac:
        #   imageName: 'macos-10.14'
        #   rid: 'osx-x64'
        windows:
          rid: 'windows-x64'
          imageName: 'windows-2019'

    pool:
      vmImage: $(imageName)

    variables:
      buildConfiguration: 'Release'

    steps:
      - task: CMake@1
        inputs:
          workingDirectory: 'src'
          cmakeArgs: '.'
      - task: VSBuild@1        
        displayName: 'Build Windows native assets'
        condition: eq(variables.rid, 'windows-x64')
        inputs:
          solution: 'src/libfacedetection.net.sln'
          platform: 'x64'
          configuration: '$(buildConfiguration)'