trigger:
- master

variables:
  versionprefix: 0.1.0

jobs:
  - job: 'BuildLib'  
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-18.04'
          rid: 'linux-x64'
        # mac:
        #   imageName: 'macos-10.14'
        #   rid: 'osx-x64'
        windows:
          rid: 'windows-x64'
          imageName: 'windows-2019'

    pool:
      vmImage: $(imageName)

    variables:
      buildConfiguration: 'Release'
      libname: 'libfacedetection.net'

    steps:
      - task: CMake@1
        inputs:
          workingDirectory: 'src'
          cmakeArgs: '.'
      - task: VSBuild@1
        displayName: 'Build Windows native assets'
        condition: eq(variables.rid, 'windows-x64')
        inputs:
          solution: 'src/libfacedetection.net.sln'
          platform: 'x64'
          configuration: '$(buildConfiguration)'
      
      - task: Bash@3
        displayName: 'Build Linux native assets'
        condition: eq(variables.rid, 'linux-x64')        
        inputs:
          targetType: 'inline'
          workingDirectory: src
          script: |
            make
      
      - task: CopyFiles@2
        displayName: 'Copy native binary'
        inputs:
          Contents: |
            **\$(libname).dll
            **/$(libname).so
          TargetFolder: 'artifacts'
          CleanTargetFolder: true
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'artifacts'
          ArtifactName: 'artifacts-$(rid)'
          publishLocation: 'Container'

  - job: 'BuildPackage'
    dependsOn: 'BuildLib'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'src/libfacedetection.net/native'
        artifactName: 'artifacts-windows-x64'
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: 'src/libfacedetection.net/native'
        artifactName: 'artifacts-linux-x64'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '-c $(buildConfiguration)'
        projects: 'libfacedetection.net.csproj'
        workingDirectory: 'src/libfacedetection.net'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        arguments: '-c $(buildConfiguration) /p:VersionPrefix=$(versionprefix) /p:VersionSuffix=$(Build.BuildNumber)'
        projects: 'libfacedetection.net.csproj'
        workingDirectory: 'src/libfacedetection.net'