#name: $(BuildID)
trigger:
- master

variables:
  versionprefix: 0.1.1
  buildConfiguration: 'Release'
  libname: 'libfacedetection'

jobs:
  - job: 'BuildLib'  
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-18.04'
          rid: 'linux-x64'
        # mac:
        #   imageName: 'macos-10.14'
        #   rid: 'osx-x64'
        # windows:
        #   rid: 'windows-x64'
        #   imageName: 'windows-2019'

    pool:
      vmImage: $(imageName)

    steps:
      - task: CMake@1
        inputs:
          workingDirectory: 'src'
          cmakeArgs: '.'
      - task: VSBuild@1
        displayName: 'Build Windows native assets'
        condition: eq(variables.rid, 'windows-x64')
        inputs:
          solution: 'src/libfacedetection.sln'
          platform: 'x64'
          configuration: '$(buildConfiguration)'
      
      - task: Bash@3
        displayName: 'Build Linux native assets'
        condition: eq(variables.rid, 'linux-x64')        
        inputs:
          targetType: 'inline'
          workingDirectory: src
          script: make
      
      - task: CopyFiles@2
        displayName: 'Copy native binary'
        inputs:
          Contents: |
            **\$(libname).dll
            **/$(libname).so
          TargetFolder: 'artifacts'
          CleanTargetFolder: true
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'artifacts'
          ArtifactName: 'artifacts-$(rid)'
          publishLocation: 'Container'

  - job: 'TestLib'
    dependsOn: 'BuildLib'
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-18.04'
          rid: 'linux-x64'
        # mac:
        #   imageName: 'macos-10.14'
        #   rid: 'osx-x64'
        windows:
          rid: 'windows-x64'
          imageName: 'windows-2019'

    pool:
      vmImage: $(imageName)

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download windows-x64 artifact'
        condition: eq(variables.rid, 'windows-x64')
        inputs:
          downloadType: 'specific'
          itemPattern: '**/$(libname).dll'
          downloadPath: 'artifacts'
          artifactName: 'artifacts-windows-x64'
      - task: DownloadBuildArtifacts@0
        displayName: 'Download linux-x64 artifact'
        condition: eq(variables.rid, 'linux-x64')
        inputs:
          downloadType: 'specific'
          itemPattern: '**/$(libname).so'
          downloadPath: 'artifacts'
          artifactName: 'artifacts-linux-x64'
      - task: CopyFiles@2
        displayName: 'Copy native binary to src/native'
        inputs:
          Contents: 'artifacts/**/*'
          TargetFolder: src/native
          flattenFolders: true        
      - task: UseDotNet@2
        displayName: 'Use .NET Core 3.1.x'
        inputs:
          packageType: 'sdk'
          version: '3.1.x'
      - task: CmdLine@2
        displayName: 'Install linux dependencies'
        condition: eq(variables.rid, 'linux-x64')
        inputs:
          script: 'sudo apt-get update && sudo apt-get install libc6-dev libgdiplus'
      - task: DotNetCoreCLI@2
        displayName: 'Build libfacedetection.net'
        inputs:
          command: 'build'
          projects: 'libfacedetection.net.sln'
          arguments: '--configuration $(buildConfiguration)'
      # - task: CmdLine@2
      #   inputs:
      #     script: 'ls src/libfacedetection.net/bin/Release/netstandard2.1/*'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'src/libfacedetection.net/bin/Release/netstandard2.1'
          ArtifactName: 'temp'
          publishLocation: 'Container'
      # - task: DotNetCoreCLI@2
      #   displayName: 'Test libfacedetection.net'
      #   inputs:
      #     command: 'test'
      #     projects: 'libfacedetection.net.sln'
      #     arguments: '--configuration $(buildConfiguration)'
      - task: CmdLine@2
        displayName: 'Test libfacedetection.net'
        inputs:
          script: 'dotnet test -c $(buildConfiguration) -v d'

  - job: 'BuildPackage'
    dependsOn: 'TestLib'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download windows-x64 artifact'
      inputs:
        downloadType: 'specific'
        itemPattern: '**/$(libname).dll'
        downloadPath: 'artifacts'
        artifactName: 'artifacts-windows-x64'
    - task: DownloadBuildArtifacts@0
      displayName: 'Download linux-x64 artifact'
      inputs:
        downloadType: 'specific'
        itemPattern: '**/$(libname).so'
        downloadPath: 'artifacts'
        artifactName: 'artifacts-linux-x64'
    - task: CopyFiles@2
      displayName: 'Copy native binary to src/native'
      inputs:
        Contents: 'artifacts/**/*'
        TargetFolder: src/native
        flattenFolders: true        
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1.x'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - task: CmdLine@2
      displayName: 'Package libfacedetection.net'
      inputs:
        script: 'dotnet pack -c $(buildConfiguration) /p:VersionPrefix=$(versionprefix) -o $(Build.ArtifactStagingDirectory)'
        workingDirectory: 'src/libfacedetection.net'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'package'
        publishLocation: 'Container'

  # - job: 'PublishToNuGet'
  #   dependsOn: 'BuildPackage'
  #   steps:
  #   - task: DownloadBuildArtifacts@0
  #     inputs:
  #       downloadPath: 'artifacts'
  #       artifactName: 'package'
  #   - task: NuGetCommand@2
  #     displayName: 'Publish to nuget.org'
  #     inputs:
  #       command: push
  #       packagesToPush: 'artifacts/package/*.nupkg;!artifacts/package/*.symbols.nupkg'
  #       nuGetFeedType: external
  #       publishFeedCredentials: 'NuGet'